### ISSUE TITLE
Cannot disable temporary files

### ISSUE THREAD

**Issue by kewp** [clemos/haxe-sublime-bundle#231] opened 2015-05-09 09:55 UTC
I can't figure out how to disable the .tmp files that keep getting generated ... Is there a setting for that ?

**Comment by r3a1ay** [comment] 2015-05-09 13:06
There is no setting for that.
To get completion list, the file should be saved. Currently the file is saved and restored from a temp file (to restore its unsaved state on disc).
I can add an option to disable temp file generation. But the file will be save on every code completion. To restore it you'll have to use undo history.

**Comment by kewp** [comment] 2015-05-09 13:51
That's interesting - Can you not disable saves on completion completely ?

Also - Is there a way to disable completion ?

**Comment by r3a1ay** [comment] 2015-05-09 14:10
I think its impossible. The file should be saved.
You can disable autocompletion in user settings (to display the code completion list manually press `ctrl+space` or `alt+/`):
```js
"auto_complete": false
```
But you will lost sublime's completions as well. 
Tomorrow I'll add an option to disable haxe's autocompletion only.

**Comment by kewp** [comment] 2015-05-09 14:27
Thanks, that's brilliant.

Sorry to ask again, but - Why do you need to save a file during an autocomplete ?

**Comment by r3a1ay** [comment] 2015-05-09 14:39
This bundle uses [compiler based](http://haxe.org/manual/cr-completion-overview.html) code completions.

**Comment by kewp** [comment] 2015-05-09 14:42
Ok, that makes sense then ...

**Comment by kewp** [comment] 2015-05-09 17:46
I should mention why this was an issue - I was getting temporary files left after closing sublime. Surely they should be removed once the completion is finished ?

**Comment by r3a1ay** [comment] 2015-05-09 19:08
Yes, they should.
Check sublime's console (View-Show console) for errors.

**Comment by kewp** [comment] 2015-05-09 19:19
Ok, got it - going to have to wait for the problem to reappear ...

I got this error saying "Game.hx has changed - do you want to reload it?".
I'm never sure why it says that or what to do. Does this have to do with
auto completion?

**Comment by r3a1ay** [comment] 2015-05-09 19:27
It seems that you have some issue. Maybe this one #225.
I'll check that tomorrow.

**Comment by kewp** [comment] 2015-05-09 19:31
Yes - Seems like it happens when I use auto complete - Any changes I made before the save are lost if I click OK ...

It sort of makes sense, though, right - Based on what you were saying about saving before completes ? Though I suppose that's the point of temporary files ...

I should mention I have the following settings (which are the opposite of standard):

    "hot_exit": false,
    "remember_open_files": false,
    "close_windows_when_empty": true

**Comment by r3a1ay** [comment] 2015-05-09 19:35
Can you upload somewhere a test hx file with this issue and build file?

**Comment by kewp** [comment] 2015-05-09 19:35
Yes - Turning hot exit back on removes the message "File changed on disc. Reload?"

**Comment by kewp** [comment] 2015-05-09 19:39
You still want a ... test hx file ? Not sure what you mean ...

**Comment by r3a1ay** [comment] 2015-05-09 19:46
Can't reproduce the issue with `hot_exit = false`.
No. I'll add some debug code tomorrow.

**Comment by kewp** [comment] 2015-05-09 19:47
Ok cool. Thanks for the help.

**Comment by r3a1ay** [comment] 2015-05-10 13:45
Added `haxe_auto_complete` setting.
Set it to `false` if you want to display haxe completion manually (**ctrl+space** or `haxe_display_completion` command).

Please try to reproduce "reload" issue. And check sublime's console for errors.

**Comment by kewp** [comment] 2015-05-10 13:57
Thanks, r3a1ay.

Can reproduce error fine: as soon as I disable hot_exit, make some changes, do a haxe-based auto complete, switch to another window (not sublime), and come back I get a "... Has changed on disk. Do you want to reload?" message. Which when I click OK wipes my changes ... And when I put hot_exit back to true and restart sublime the problem goes away ... Have checked several times.

**Comment by r3a1ay** [comment] 2015-05-10 13:58
`"haxe_auto_complete": false` disables method hints. 
Press **ctrl+shift+h, ctrl+shift+p** to display the hints manually.

Do you have some error messages in sublime's console?

**Comment by kewp** [comment] 2015-05-10 14:02
I'm sorry - I forgot to check.

I did have some errors, strangely (had nothing yesterday) - But they were before I tried turning hot exit on/off to retest reload error.

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 236, in on_query_completions
  File ".\HaxeComplete.py", line 1815, in on_query_completions
  File ".\HaxeComplete.py", line 1973, in get_haxe_completions
  File ".\HaxeComplete.py", line 1779, in run_haxe
  File ".\features\haxe_errors.py", line 66, in highlight_errors
AttributeError: 'module' object has no attribute 'samefile'

**Comment by r3a1ay** [comment] 2015-05-10 14:03
Thanks. That should help.

**Comment by r3a1ay** [comment] 2015-05-10 14:26
Should be fixed.
Please check.

**Closed** 2015-05-10 14:25 UTC

**Comment by kewp** [comment] 2015-05-10 14:30
Woohoo - works great. And it also seems a LOT faster !
