### ISSUE TITLE
Strange completion results with -net-lib assembly contents

### ISSUE THREAD

**Issue by JeriXNet** [clemos/haxe-sublime-bundle#184] opened 2015-01-20 20:56 UTC
I don't know is this right place to address this issue. Maybe it's not even an issue, but anyway, here what bothers me.
I've seen this picture in [nadako's blog post](http://nadako.tumblr.com/post/78559625982/haxe-3-1-is-here):
![d8np0](https://cloud.githubusercontent.com/assets/7815518/5825829/54ab27c0-a0ff-11e4-8855-227dfc36ed9b.png)
But in my current setup I got this:
![2015-01-20_234817](https://cloud.githubusercontent.com/assets/7815518/5825838/62fa5c92-a0ff-11e4-964f-54990d064f3c.jpg)
And I can't get it to work properly. Even tried clean installation of sublime with just package control and haxe-sublime-bundle installed.

**Comment by JeriXNet** [comment] 2015-02-03 18:34
build 3065

**Comment by clemos** [comment] 2015-02-04 08:41
It seems @nadako uses either the refactoring branch or the haxe-port branch:
https://github.com/nadako/haxe-sublime-bundle/tree/6e09a2acea0d6f9cb741e2b560c2250c265155b1
Maybe he can confirm :)

**Comment by nadako** [comment] 2015-02-04 09:08
I'm on the main branch nowadays and I'm also getting those `(...)` signatures. Fix plox!

**Comment by clemos** [comment] 2015-02-04 09:22
We did that because ST trimmed the completions at some time, which was pretty ugly.
If it doesn't do that anymore, I'll just remove our trimming code.

**Comment by clemos** [comment] 2015-02-05 11:17
I made a quick test, and it doesn't seem possible to widen the autocomplete list currently (build 3065 / Ubuntu)...
Any hint as to how you managed to do it @nadako ?

**Comment by nadako** [comment] 2015-02-05 11:51
I'm not sure what the problem is, it worked fine in my toy plugin here https://github.com/nadako/hxsublime

**Comment by clemos** [comment] 2015-02-06 14:07
@nadako how about the `haxe-port` version ? I see there has been quite a lot of work around it. Is it useable ?

**Comment by nadako** [comment] 2015-02-06 14:09
I think it's abandoned right now due to lack of @frabbit's time

**Comment by clemos** [comment] 2015-04-13 08:41
Closing the issue, as it seems due to Sublime Text itself

**Closed** 2015-05-01 08:26 UTC
